version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_USER=nginx
    restart: unless-stopped 